config/routes.rb
TwitterResearch::Application.routes.draw do

  devise_for :users

  root(:to => 'searches#index') #setting up root index action
  resources(:searches)
  resources(:categories)

  resources(:tweets) do
    resources(:notes)
    end

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible (:title)
  validates(:title, presence: true, uniqueness: true)
  has_and_belongs_to_many(:tweets)
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible(:note_text)
  validates(:note_text, presence: true)
  belongs_to(:tweet)
  belongs_to(:user)
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible(:twitter_user, :tweeted_text, :tweeted_at, :categories_as_string)
  #allows mass assignment. never put a foriegn key in here.
  #only what you want a user to be able to use

  validates(:twitter_user, :presence =>true)
  validates(:tweeted_text, :presence =>true)
  validates(:tweeted_at, :presence => true)
  #validates(:user_id, :presence => true)

  scope(:with_notes, includes(:notes).order('notes.created_at desc'))
  belongs_to(:user)
  has_many(:notes)
  has_and_belongs_to_many(:categories)

  def suggested_categories
    categories = Category.all.map(&:title).map(&:downcase)
    tweet = tweeted_text.gsub(/[^\w\s]/, ' ').downcase.split.sort
    same = tweet & categories
    same.map(&:capitalize).sort.join(', ')
  end

  ###########################################
#Returns a comma separated string of the current category titles.
  def categories_as_string
    categories.map(&:title).sort.join(', ')

  end
  ##################################################
  #Given a comma separated string of category titles, reset the categories
  #for this tweet to the categories in the string.

  def categories_as_string=(new_categories)
    categories.clear

    new_categories.split(/\s*, \s*/).each do |title|
      cat = Category.where('LOWER(title) = ?', title.downcase).first
      categories << cat if !cat.nil?
      #if !cat.nil?
      # categories << cat

    end
  end

  end

    #String#split
    #String#downcase
    #text = tweeted_text.gsub(/#/, '')
    #titles = Category.all.map(&:title).map
    #titles.include?(word)

# def suggested_categories
#words = tweeted_text.gsub(/#/, '').split(/\s+/)
#categories = Catgory.limit(30).all

#words.inject([]) do |collector, word|
#match = categories.detect {|c| c.title_match?(word)}
#collector << match.title if match
#collector
#end.sort.join(',')
#end
#end

# class Category < ActiveRecord::Base



#def title_match?(other)
#title.downcase = x

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  attr_accessible(:full_name, :email)

  validates(:full_name, :presence =>true)
  validates(:email, :presence =>true, :uniqueness => true)

  has_many(:tweets)

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  respond_to(:html, :json, :js)
  before_filter(:authenticate_user!)
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.order(:title).limit(50)
    respond_with(@categories)
  end

  def show
    @category = Category.includes(:tweets).
      order('tweets.tweeted_at desc').find(params[:id])
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def create
    @category = Category.create(params[:category])
    respond_with(@category, location: categories_url)
  end

  def edit
    @category = Category.find(params[:id])
    respond_with(@category)
  end

  def update
    @category = Category.find(params[:id])
    @category.update_attributes(params[:category])
    respond_with(@category, location: categories_url)
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    respond_with(@category)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_filter(:fetch_tweet)
  before_filter(:fetch_note, except: [:index, :new, :create])

  def index
    @notes = @tweet.notes.order('created_at desc')
    respond_with([@tweet, @notes], location: tweet_url(@tweet))
  end

  def show
    # @note = @tweet.notes.find(params[:id])
    respond_with([@tweet, @note], location: tweet_url(@tweet))
  end

  def new
    @note = @tweet.notes.build
    respond_with([@tweet, @note])
  end

  def create
    @note = @tweet.notes.create(params[:note])
    respond_with([@tweet, @note], location: tweet_url(@tweet))
  end

  def edit
    # @note = @tweet.notes.find(params[:id])
    respond_with([@tweet, @note])
  end

  def update
    # @note = @tweet.notes.find(params[:id])
    @note.update_attributes(params[:note])
    respond_with([@tweet, @note])
  end

  def destroy
    # @note = @tweet.notes.find(params[:id])
    @note.destroy
    respond_with([@tweet, @note])
  end

  #########################################################################
  private

  def fetch_tweet
    @tweet = current_user.tweets.find(params[:tweet_id])
  end

  def fetch_note
    @note = @tweet.notes.find(params[:id])
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
  end

  def show
    #debugger
    search = SimpleTwitter::Search.new
    search.per_page = params[:rpp]
    flash.notice = "I just did your search."
    @results=search.search(params[:q])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = current_user.tweets.order('tweeted_at desc').limit(25)
    respond_with(@tweets)
  end

  def show
    @tweet = current_user.tweets.with_notes.find(params[:id])
    respond_with(@tweet)
  end

  def create
    @tweet = current_user.tweets.create(params[:tweet])
    respond_with(@tweet, :location => tweets_url)
  end

  def edit
    @tweet = current_user.tweets.find(params[:id])
    respond_with(@tweet)
  end

  def update
    @tweet = current_user.tweets.find(params[:id])
    @tweet.update_attributes(params[:tweet])
    respond_with(@tweet)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/categories/_category.html.erb
<li id="<%= dom_id(category) %>">
  <span class="title">
    <%= link_to(category.title, category_url(category))%>
  </span>

  <span class="edit">
    <%= link_to('Edit', edit_category_url(category)) %>
  </span>

  <span class="delete">
    <%= link_to('Delete', category_url(category),
                :method => :delete,
                :remote => true,
                :confirm => 'Are you sure you want to delete?') %>
  </span>
</li>

app/views/categories/_form.html.erb
<%= form_for(@category, :remote => true) do |form| %>
  <fieldset>
    <legend>Category</legend>

    <div>
      <%= form.label(:title)%>
      <%= form.text_field(:title)%>
    </div>

    <div>
      <%= form.submit%>
    </div>
  </fieldset>
  <% end %>

app/views/categories/create.js.erb
$(function () {
  $("#new-form").fadeOut();

  var html = "<%= j(render(partial: 'category', object: @category))%>";
  $("#categories").append(html);

});

app/views/categories/destroy.js.erb
$(function () {
  $("#<%= dom_id(@category) %>").fadeOut();
});

app/views/categories/edit.html.erb
<%= render(partial: 'form')%>

app/views/categories/index.html.erb
<h1>
  Categories (<%= link_to('New', new_category_url, :remote =>true)%>)
</h1>

<div id="new-form"></div>

<ul id="categories">
  <%= render(:partial => 'category', :collection => @categories)%>
</ul>

app/views/categories/new.html.erb
<%= render(partial:'form')%>

app/views/categories/new.js.erb
$(function () {
  var html = "<%= j(render(partial: 'form'))%>";
  $("#new-form").html(html).show();
});

app/views/categories/show.html.erb
<h1>Tweets in <%= @category.title %></h1>

<ul>
  <%= render(partial: 'tweets/tweet', collection: @category.tweets)%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterResearch</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% if user_signed_in? %>
      <nav>
        <ul>
          <li> <%= link_to('Search Twitter', searches_url) %></li>
          <li><%= link_to('My Saved Tweets', tweets_url)%></li>
          <li><%= link_to('My Categories', categories_url)%></li>

          <li>
            <%= link_to('Log Out', destroy_user_session_url,
                        :method => :delete,
                        :data => {:confirm => "Are you sure you want to logout?"})%>
          </li>

        </ul>
      </nav>
    <% end %>

    <% if !flash.empty? %>
      <div>
        <p><%= flash.notice %></p>
        <p><%= flash.alert %></p>
    </div>
    <% end %>

    <div id="content">
      <%= yield %>
    </div>

  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for([@tweet, @note]) do |form|%>
  <fieldset>
    <legend>Note</legend>

    <div>
      <%= form.label(:note_text)%>
      <%= form.text_area(:note_text)%>
    </div>

    <div>
      <%= form.submit %>
    </div>
  </fieldset>
<% end %>

app/views/notes/_show.html.erb
<div>
  <span class= "time"><%= show.created_at %></span>
  <p><%= show.note_text %></p>
  </div>

app/views/notes/edit.html.erb
<%= render(:partial => "form")%>

app/views/notes/new.html.erb
<%= render(:partial => "form")%>

app/views/searches/index.html.erb
<form action="/searches/1" method="get">
  <label>Search Twitter</label>
  <input type="text" name="q"/>

  <label>Results Per Page</label>
  <input type="rpp" name="rpp"/>
  <input type="submit" name="submit" value="Search"/>
 </form>

app/views/searches/show.html.erb
<h1>You searched for: <div> <%=params[:q] %><div><h1>

        <ol>
          <% @results.each do |r|%>
            <li><img src="<%=r.user_image_url%>" height = "42", width = "42"/>
              <%= r.user%>:<div> <%=r.text%><div> Date & Time: <%=r.time_stamp%>
                  <%tweet = Tweet.new(:twitter_user => r.user,
                                      :tweeted_text => r.text,
                                      :tweeted_at => r.time_stamp)%>

                  <%= form_for(tweet) do |form|%>
                    <%= form.hidden_field(:twitter_user)%>
                    <%= form.hidden_field(:tweeted_text)%>
                    <%= form.hidden_field(:tweeted_at)%>
                    <%= form.submit('Save')%>
                    <%end%>
            </li>
            <% end %>
        </ol>

app/views/tweets/_tweet.html.erb
<li>
  <%= tweet.twitter_user %> said <%= tweet.tweeted_text %>
  <%= link_to('View', tweet_url(tweet))%>
   </li)>

app/views/tweets/edit.html.erb
<%= form_for(@tweet) do |form| %>
  <fieldset>
    <!-- Hi, I'm app/views/tweets/edit.html.erb -->
    <legend>Edit a Tweet's Categories</legend>

    <div>
      <%= form.label(:categories_as_string, 'Categories')%>
      <%= form.text_field(:categories_as_string)%>
    </div>

    <%= form.submit%>
  </fieldset>
<% end %>

<h2>Available Categories</h2>

<ul>
  <% Category.order(:title).each do |c| %>
    <li><%= c.title %></li>
  <% end %>
</ul>

app/views/tweets/index.html.erb
<ol>
  <% @tweets.each do |tweet| %>
    <li>
      [ID: <%= tweet.id %>]
      <%= tweet.twitter_user %> said <%= tweet.tweeted_text %> time <%= tweet.tweeted_at%>
      <%= link_to('View', tweet_url(tweet))%>
    </li>
  <% end %>
  <%= render(partial: 'tweet', collection: @tweets)%>
</ol>

app/views/tweets/show.html.erb
<div class = "tweet">
  <h2> Tweet Info: </h2>
  <span>
    On <%= @tweet.tweeted_at %>, <%= @tweet.twitter_user %> said:
  </span>

  <p><%= @tweet.tweeted_text %> </p>
</div>

<div class="categories">
  <h2>Categories <%= link_to('Edit', edit_tweet_url(@tweet)) %></h2>
  <% if @tweet.categories.empty? %>
    <p>This tweet isn't in any categories.<p>
    <% else %>
    <p><%= @tweet.categories.map(&:title).to_sentence %></p>
  <% end %>
</div>

<div class = "notes">
  <h2>My Notes:</h2>
  <span><%= link_to('Create New Note', new_tweet_note_url(@tweet))%>
  </span>

  <%= render(partial: 'notes/show', collection: @tweet.notes)%>
</div>